import { describe, expect, it } from 'vitest';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { scanRepo } from '../src/adapters/repo.js';
import { loadSchedule } from '../src/core/tiering.js';
import { buildReport } from '../src/reporters/json.js';
import { renderHtml } from '../src/reporters/html.js';
import { renderMarkdown } from '../src/reporters/md.js';

const fixture = join(dirname(fileURLToPath(import.meta.url)), 'fixtures', 'sample-sfdx-repo');
const report = buildReport(scanRepo(fixture), loadSchedule(), {
  mode: 'repo',
  target: { path: fixture },
  scheduleSource: 'built-in retirement-schedule.json',
  scannerVersion: '0.0.0-test',
});

describe('HTML reporter', () => {
  const html = renderHtml(report);

  it('is self-contained: no scripts, no external resources', () => {
    expect(html).not.toMatch(/<script/i);
    expect(html).not.toMatch(/<link/i);
    expect(html).not.toMatch(/src=/i);
    expect(html).not.toMatch(/@import/i);
    // The only URL allowed is the footer CTA anchor.
    const urls = html.match(/https?:\/\/[^"'\s<]+/g) ?? [];
    expect(urls).toEqual(['https://ideabulut.com']);
  });

  it('leads with a date-led headline banner', () => {
    expect(html).toContain("Already failing - retired Summer '25 (REST 410 / SOAP 500 / Bulk 400)");
    expect(html).toContain("Retires Summer '28");
    expect(html.indexOf('banner')).toBeLessThan(html.indexOf('<table'));
  });

  it('shows summary tiles, component table, and footer CTA', () => {
    expect(html).toContain('debt score');
    expect(html).toContain('AncientHelper.cls-meta.xml');
    expect(html).toContain('(inherited)');
    expect(html).toContain('Generated by <strong>Almanac</strong>');
  });

  it('escapes HTML in user-controlled strings', () => {
    const evil = {
      ...report,
      warnings: [{ code: 'x', message: '<img src=x onerror=alert(1)>' }],
    };
    expect(renderHtml(evil)).not.toContain('<img src=x');
  });
});

describe('Markdown reporter', () => {
  const md = renderMarkdown(report);

  it('renders headline blockquotes and a component table', () => {
    expect(md).toContain("> ⚠ **1 item — Already failing - retired Summer '25 (REST 410 / SOAP 500 / Bulk 400)** (Jun 2025)");
    expect(md).toContain('| Tier | Date | API version | Type | Location |');
    expect(md).toContain('`force-app/main/default/classes/AncientHelper.cls-meta.xml`');
  });

  it('shows identical dates to the report headlines', () => {
    for (const h of report.headlines) {
      expect(md).toContain(h.message);
    }
  });
});
