/**
 * Markdown reporter — same content as HTML, shaped for PR
 * comments. Renders entirely from the Report object so dates are identical.
 */
import type { Report } from './json.js';

function fmtDate(yyyyMm: string): string {
  const [y, m] = yyyyMm.split('-');
  const names = ['', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
  return `${names[Number(m)] ?? m} ${y}`;
}

export function renderMarkdown(report: Report): string {
  const lines: string[] = [];
  lines.push('## Almanac — API version debt report');
  lines.push('');

  if (report.headlines.length === 0) {
    lines.push('✅ **No dated API version debt found.**');
  } else {
    for (const h of report.headlines) {
      lines.push(`> ⚠ **${h.message}** (${fmtDate(h.date)})`);
    }
  }
  lines.push('');
  lines.push(
    `**Debt score: ${report.debtScore}** (0 = clean) · ${report.summary.totalComponents} components · ${report.summary.totalIntegrations} integrations · mode: ${report.mode}`,
  );
  lines.push('');

  lines.push('| Tier | Date | API version | Type | Location |');
  lines.push('|---|---|---|---|---|');
  for (const c of report.components) {
    const version = `${c.apiVersion ?? '?'}${c.versionSource === 'inherited' ? ' _(inherited)_' : ''}`;
    lines.push(
      `| ${c.tier} | ${c.retirementDate ? fmtDate(c.retirementDate) : '—'} | ${version} | ${c.type} | \`${c.location}\` |`,
    );
  }
  lines.push('');

  if (report.integrations.length > 0) {
    lines.push('### Integrations');
    lines.push('');
    lines.push('| Tier | Date | Client | API family | Version | Requests |');
    lines.push('|---|---|---|---|---|---|');
    for (const i of report.integrations) {
      lines.push(
        `| ${i.tier} | ${i.retirementDate ? fmtDate(i.retirementDate) : '—'} | ${i.clientName} | ${i.apiFamily}${i.type === 'soap-login' ? ' **login()**' : ''} | ${i.apiVersion} | ${i.requestCount ?? '—'} |`,
      );
    }
    lines.push('');
  }

  if (report.warnings.length > 0) {
    lines.push('### Warnings');
    lines.push('');
    for (const w of report.warnings) {
      lines.push(`- \`${w.code}\` ${w.message}${w.location ? ` — \`${w.location}\`` : ''}`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push(
    `_Generated by Almanac (idea-almanac ${report.scanner.version}) · current API version ${report.schedule.currentApiVersion}._`,
  );
  lines.push('');
  return lines.join('\n');
}
